schemaVersion: 2.2.0
metadata:
  name: marleixo-frontend
  displayName: React
  description: "Mine all mine"
  icon: https://raw.githubusercontent.com/devfile-samples/devfile-stack-icons/main/react.svg
  tags:
    - Node.js
    - React
  projectType: React
  language: TypeScript
  provider: Marcio Aleixo
  version: 1.0.0
starterProjects:
  - name: react-frontend
    git:
      checkoutFrom:
        revision: main
      remotes:
        origin: https://github.com/marleixo/ts-react-frontend.git
components:
  - container:
      endpoints:
        - name: https-react
          targetPort: 3000
          protocol: https
      image: ubi9/nodejs-20
      # args: ["tail", "-f", "/dev/null"]
      memoryLimit: 1024Mi
    name: runtime
commands:
  - exec:
      commandLine: npm install
      component: runtime
      group:
        isDefault: true
        kind: build
      workingDir: ${PROJECT_SOURCE}
    id: install
  - exec:
      commandLine: npm run dev
      component: runtime
      group:
        isDefault: true
        kind: run
      workingDir: ${PROJECT_SOURCE}
    id: run
