schemaVersion: 2.2.0
metadata:
  name: marleixo-frontend
components:
  - name: runtime
    container:
      image: quay.io/devfile/universal-developer-image
      endpoints:
        - name: https-react
          targetPort: 3000
          protocol: https
      args: ["tail", "-f", "/dev/null"]
      memoryLimit: 2G
commands:
  - id: install
    exec:
      commandLine: npm install
      component: runtime
      group:
        kind: build
      workingDir: ${PROJECT_SOURCE}
  - id: run
    exec:
      commandLine: npm run dev
      component: runtime
      group:
        kind: run
      workingDir: ${PROJECT_SOURCE}
